;this file for FamiTone2 library generated by text2data tool

TestMusic3_music_data:
	.byte 2
	.word .Linstruments
	.word .Lsamples-3
	.word .Lsong0ch0,.Lsong0ch1,.Lsong0ch2,.Lsong0ch3,.Lsong0ch4,307,256 ; Caribou
	.word .Lsong1ch0,.Lsong1ch1,.Lsong1ch2,.Lsong1ch3,.Lsong1ch4,307,256 ; Pause

.Linstruments:
	.byte $b0 ;instrument $00
	.word .Lenv1,.Lenv0,.Lenv0
	.byte $00
	.byte $b0 ;instrument $01
	.word .Lenv2,.Lenv0,.Lenv0
	.byte $00
	.byte $b0 ;instrument $02
	.word .Lenv3,.Lenv0,.Lenv0
	.byte $00
	.byte $b0 ;instrument $03
	.word .Lenv4,.Lenv0,.Lenv0
	.byte $00

.Lsamples:
	.byte $00+__dpcm_offset,$36,$0f	;1
.Lenv0:
	.byte $c0,$00,$00
.Lenv1:
	.byte $c6,$cf,$cc,$c9,$c7,$c6,$c5,$c4,$c2,$00,$08
.Lenv2:
	.byte $c3,$c7,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$08
.Lenv3:
	.byte $c4,$c3,$c2,$c1,$c0,$00,$04
.Lenv4:
	.byte $c2,$06,$c1,$00,$02


; Caribou
.Lsong0ch0:
	.byte $fb,$07
.Lsong0ch0loop:
.Lref0:
	.byte $80,$3a,$85,$84,$30,$80,$32,$83,$2c,$91,$2d,$33,$37,$38,$87,$36
	.byte $83
.Lref1:
	.byte $3a,$85,$84,$30,$80,$32,$83,$2c,$91,$33,$33,$33,$30,$30,$83,$30
	.byte $85
.Lref2:
	.byte $3a,$85,$84,$30,$80,$32,$83,$2c,$91,$2d,$33,$37,$38,$87,$36,$83
.Lref3:
	.byte $81,$32,$33,$33,$33,$30,$85,$31,$29,$36,$37,$37,$37,$32,$83,$31
	.byte $29,$30,$81
.Lref4:
	.byte $33,$00,$85,$31,$33,$00,$85,$31,$33,$00,$85,$31,$32,$85,$36,$85
.Lref5:
	.byte $33,$00,$85,$31,$33,$00,$85,$31,$33,$00,$85,$31,$33,$29,$29,$82
	.byte $28,$81
	.byte $ff,$0e
	.word .Lref0
	.byte $ff,$0f
	.word .Lref1
	.byte $ff,$0e
	.word .Lref2
	.byte $ff,$13
	.word .Lref3
	.byte $ff,$10
	.word .Lref4
	.byte $ff,$11
	.word .Lref5
	.byte $fd
	.word .Lsong0ch0loop

; Caribou
.Lsong0ch1:
.Lsong0ch1loop:
.Lref12:
	.byte $00,$85,$82,$14,$85,$00,$85,$15,$00,$89,$14,$85,$1b,$01,$1f,$00
	.byte $81
.Lref13:
	.byte $00,$85,$14,$85,$00,$85,$15,$00,$89,$14,$85,$1b,$01,$1f,$00,$81
	.byte $ff,$10
	.word .Lref13
	.byte $ff,$10
	.word .Lref13
	.byte $ff,$10
	.word .Lref13
	.byte $ff,$10
	.word .Lref13
.Lref18:
	.byte $81,$84,$52,$87,$4a,$83,$52,$87,$4a,$83,$52,$87,$4a,$83,$4e,$87
	.byte $4e,$81
.Lref19:
	.byte $81,$52,$87,$4a,$83,$52,$87,$4a,$83,$52,$87,$4a,$85,$49,$48,$85
.Lref20:
	.byte $81,$52,$87,$4a,$83,$52,$87,$4a,$83,$52,$87,$4a,$83,$4e,$87,$4e
	.byte $81
.Lref21:
	.byte $81,$52,$53,$53,$53,$4e,$85,$4f,$49,$4e,$4f,$4f,$4f,$48,$83,$49
	.byte $40,$85
	.byte $ff,$10
	.word .Lref12
	.byte $ff,$10
	.word .Lref13
	.byte $fd
	.word .Lsong0ch1loop

; Caribou
.Lsong0ch2:
.Lsong0ch2loop:
.Lref24:
	.byte $80,$4b,$3b,$01,$3b,$4b,$3b,$01,$3b,$4b,$3b,$01,$3b,$4b,$3b,$01
	.byte $3a,$81
.Lref25:
	.byte $4b,$3b,$01,$3b,$4b,$3b,$01,$3b,$4b,$3b,$01,$3b,$4b,$3b,$01,$3a
	.byte $81
	.byte $ff,$11
	.word .Lref25
	.byte $ff,$11
	.word .Lref25
	.byte $ff,$11
	.word .Lref25
	.byte $ff,$11
	.word .Lref25
	.byte $ff,$11
	.word .Lref25
	.byte $ff,$11
	.word .Lref25
	.byte $ff,$11
	.word .Lref25
	.byte $ff,$11
	.word .Lref25
	.byte $ff,$11
	.word .Lref25
	.byte $ff,$11
	.word .Lref25
	.byte $fd
	.word .Lsong0ch2loop

; Caribou
.Lsong0ch3:
.Lsong0ch3loop:
.Lref36:
	.byte $84,$13,$13,$00,$82,$16,$86,$1b,$84,$13,$13,$00,$82,$16,$86,$1b
	.byte $84,$13,$13,$00,$82,$16,$86,$1b,$84,$13,$13,$00,$82,$16,$86,$1a
	.byte $81
	.byte $ff,$15
	.word .Lref36
	.byte $ff,$15
	.word .Lref36
	.byte $ff,$15
	.word .Lref36
	.byte $ff,$15
	.word .Lref36
	.byte $ff,$15
	.word .Lref36
	.byte $ff,$15
	.word .Lref36
	.byte $ff,$15
	.word .Lref36
	.byte $ff,$15
	.word .Lref36
	.byte $ff,$15
	.word .Lref36
	.byte $ff,$15
	.word .Lref36
	.byte $ff,$15
	.word .Lref36
	.byte $fd
	.word .Lsong0ch3loop

; Caribou
.Lsong0ch4:
.Lsong0ch4loop:
.Lref48:
	.byte $bf
.Lref49:
	.byte $bf
.Lref50:
	.byte $bf
.Lref51:
	.byte $bf
.Lref52:
	.byte $bf
.Lref53:
	.byte $bf
.Lref54:
	.byte $bf
.Lref55:
	.byte $bf
.Lref56:
	.byte $bf
.Lref57:
	.byte $bf
.Lref58:
	.byte $bf
.Lref59:
	.byte $bf
	.byte $fd
	.word .Lsong0ch4loop


; Pause
.Lsong1ch0:
	.byte $fb,$06
.Lsong1ch0loop:
.Lref60:
	.byte $bf
	.byte $fd
	.word .Lsong1ch0loop

; Pause
.Lsong1ch1:
.Lsong1ch1loop:
.Lref61:
	.byte $bf
	.byte $fd
	.word .Lsong1ch1loop

; Pause
.Lsong1ch2:
.Lsong1ch2loop:
.Lref62:
	.byte $82,$33,$00,$89,$33,$00,$89,$33,$00,$89,$2d,$01,$2c,$85
	.byte $fd
	.word .Lsong1ch2loop

; Pause
.Lsong1ch3:
.Lsong1ch3loop:
.Lref63:
	.byte $84,$16,$00,$83,$16,$00,$83,$16,$00,$83,$12,$00,$83,$16,$00,$83
	.byte $16,$00,$83,$16,$00,$83,$12,$00,$83
	.byte $fd
	.word .Lsong1ch3loop

; Pause
.Lsong1ch4:
.Lsong1ch4loop:
.Lref64:
	.byte $bf
	.byte $fd
	.word .Lsong1ch4loop
