;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word .Lntsc
	.word .Lpal
.Lntsc:
	.word .Lsfx_ntsc_0
	.word .Lsfx_ntsc_1
	.word .Lsfx_ntsc_2
.Lpal:
	.word .Lsfx_pal_0
	.word .Lsfx_pal_1
	.word .Lsfx_pal_2

.Lsfx_ntsc_0:
	.byte $83,$b8,$84,$ab,$85,$01,$02,$84,$93,$02,$84,$67,$01,$84,$3f,$07
	.byte $00
.Lsfx_pal_0:
	.byte $83,$b8,$84,$8c,$85,$01,$02,$84,$76,$02,$84,$4d,$01,$84,$29,$05
	.byte $00
.Lsfx_ntsc_1:
	.byte $83,$ba,$84,$54,$85,$00,$04,$84,$6a,$04,$84,$42,$04,$00
.Lsfx_pal_1:
	.byte $83,$ba,$84,$4e,$85,$00,$04,$84,$62,$04,$84,$3e,$02,$00
.Lsfx_ntsc_2:
	.byte $89,$3a,$8a,$0d,$01,$89,$39,$01,$89,$36,$0a,$00
.Lsfx_pal_2:
	.byte $89,$3a,$8a,$0d,$01,$89,$39,$01,$89,$36,$08,$00
